image: yussufzoulfakar/myenv:2.0

stages:
  - provisioning
  - deploying
  
variables:
  TF_WORKING_DIR: "terraform"
  K8S_MANIFEST_DIR: "kubernetes"

provision-infrastructure:
  stage: provisioning
  script:
    - cd $TF_WORKING_DIR
    - terraform init
    - terraform apply -auto-approve

    
deploy-app:
  stage: deploying
  script: 
    - aws eks update-kubeconfig --name web-page-cluster --region us-east-1
    - cd $K8S_MANIFEST_DIR
    - kubectl apply -f .
    - kubectl get all
