image: alpine:latest

stages:
  - terraform
  - deploy

variables:
  TF_WORKING_DIR: "terraform"
  K8S_MANIFEST_DIR: "kubernetes"

before_script:
  - apk add --no-cache curl unzip bash
  - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
  - rm -rf /usr/local/bin/terraform
  - unzip -o terraform.zip
  - mv terraform /usr/local/bin/terraform
  - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
  - chmod +x kubectl && mv kubectl /usr/local/bin/kubectl
  - mkdir -p ~/.kube
  - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config


terraform:
  stage: terraform
  script:
    - cd $TF_WORKING_DIR
    - terraform init
    - terraform apply -auto-approve

deploy:
  stage: deploy
  script:
    - cd $K8S_MANIFEST_DIR
    - kubectl apply -f .
