apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: yussufzoulfakar/webpage:1.0
        ports:
        - containerPort: 80